### ISSUE TITLE
The program stops when the number of threads is reached.

### ISSUE THREAD

**Issue by sgdc3** [games647/GopherProxyChecker#1]
The loop

`for i := 0; i < WORKER_THREADS; i++ {`

runs only once!

**Comment by TuxCoding** [comment]
Not for me. It creates a new goroutine every iteration. Why do you think so?

**Comment by TuxCoding** [comment]
I think I found it. It happens when there are less entries than worker threads

**Comment by sgdc3** [comment]
@games647 Sure? XD i'm testing with a 65000 entries list

**Comment by TuxCoding** [comment]
Now I understand what you mean. It stops after worker threads?

**Comment by TuxCoding** [comment]
Oh man I should clean up the code. It looks completely crazy now.

**Comment by sgdc3** [comment]
yeah, if i have 60 threads it stops after the 60th proxy

**Comment by TuxCoding** [comment]
It should be fixed with 7628fa2373fc91de3eba59c6f0023fe378aca37d

**Comment by sgdc3** [comment]
It works ;)
