### ISSUE TITLE
More readable progress counter

### ISSUE THREAD

**Issue by sgdc3** [games647/GopherProxyChecker#2]

**Comment by sgdc3** [comment]
It it possible to keep the bar in the last line ?

**Comment by TuxCoding** [comment]
This requires clearing the terminal screen like in JLine. I found no go library which can do that. Maybe there is C one which we can then bind to GO.

**Comment by sgdc3** [comment]
Someone worked on advanced stuff line https://github.com/gizak/termui

**Comment by sgdc3** [comment]
FOUND IT: https://github.com/sethgrid/multibar @games647

**Comment by TuxCoding** [comment]
Sadly https://github.com/sethgrid/multibar/issues/12

**Comment by sgdc3** [comment]
https://github.com/gosuri/uiprogress ?

**Comment by TuxCoding** [comment]
uiprogress conflicts with the logger output too although it has a higher refresh rate

**Comment by sgdc3** [comment]
Do you really need to use the logger?

**Comment by TuxCoding** [comment]
Theoretically no. I could make it configurable

**Comment by sgdc3** [comment]
What's the reason you are using the logger?

**Comment by sgdc3** [comment]
Just the timestamp?

**Comment by sgdc3** [comment]
Anyway, i sent you another contact request on skype

**Comment by TuxCoding** [comment]
> What's the reason you are using the logger?

fmt would have the same result

**Comment by sgdc3** [comment]
?

**Comment by TuxCoding** [comment]
fmt.Println has the same problems as logger on a progressbar

**Comment by sgdc3** [comment]
in my opinion you can replace the status bar with a x/total at the start of the line, remove the timestamps

**Comment by TuxCoding** [comment]
The problem is that this runs concurrent. So the output isn't ordered.

**Comment by sgdc3** [comment]
just keep a counter of the completed tasks, who cares about the order

**Comment by TuxCoding** [comment]
> Anyway, i sent you another contact request on skype

Already accepted it a long while ago
