### ISSUE TITLE
Force IPV4 on linux:

### ISSUE THREAD

**Issue by sgdc3** [games647/GopherProxyChecker#3]
`Get http://www.google.com: IPv6 is not supported by SOCKS4.
`

**Comment by sgdc3** [comment]
Looking at forums it seems that go is unable to force ipv4 xD

**Comment by TuxCoding** [comment]
Could check what result you get from: net.LookupIP("google.com")

Because I get a IPv4 address on the first index
EDIT: Using Golang 1.6.3 and Ubuntu 16.02

**Comment by sgdc3** [comment]
[2a00:1450:4007:80e::200e 216.58.208.238] <nil> on centos 6

**Comment by TuxCoding** [comment]
Is it possible that you have a IPv6 only host?

**Comment by sgdc3** [comment]
nope
