### ISSUE TITLE
0

### ISSUE THREAD

**Issue by f4nff** [games647/GopherProxyChecker#4]
0

**Comment by TuxCoding** [comment]
Please write it in english

**Comment by f4nff** [comment]
Test the process of testing:

client-->>--socks-->>--http

But when loading a lot of ip list to test, run for some time will become

client--->>--http

This bug I have caught the package to confirm!
---------------------------------
Another suggestion, because the http request will have a lot of inaccurate factors, can not use the connection tcp server.
For example, connect 192.157.192.181: 9003, and then randomly send a string, if you get the same string, it is judged to be available.

192.157.192.181:9003 code I will paste.

There is a bug, operating for a long time, will cause no response halfway, do not continue to work, this may be caused by the http module.



`package main

import (
	"bufio"
	"fmt"
	"log"
	"net"
	"time"
)

func handleConnection(conn net.Conn) {
	defer conn.Close()
	buf := make([]byte, 4096)
	reader := bufio.NewReaderSize(conn, 4096)
	writer := bufio.NewWriterSize(conn, 4096)

	for {

		conn.SetDeadline(time.Now().Add(time.Millisecond * 10))
		n, err := reader.Read(buf)
		conn.SetDeadline(time.Time{})
		if err != nil {
			nerr, ok := err.(net.Error)
			if ok {
				if nerr.Timeout() {
					//fmt.Println("read timeout n ", n, time.Now())
					time.Sleep(time.Millisecond * 10)
					continue
				} else if nerr.Temporary() {
					fmt.Println("read error: ", err)
					return
				} else {
					fmt.Println("read error: ", err)
					return
				}

			} else {
				//fmt.Println("read error: ", err)
				return
			}
		}

		if n <= 0 {
			time.Sleep(time.Millisecond * 10)
			continue
		}

		//val := string(buf[0:n])
		//fmt.Println("val: ", val)

		for pos := 0; pos < n; pos += 64 {
			end := pos + 64
			if end > n {
				end = n
			}
			_, err := writer.Write(buf[pos:end])
			if err != nil {
				fmt.Println("write error: ", err)
				return
			}

			//fmt.Println("write n: ", n)
		}
		writer.Flush()
	}
}

func main() {
	ln, err := net.Listen("tcp", ":9003")
	if err != nil {
		panic(err)
	}

	fmt.Println("listen 9003 ok")

	for {
		conn, err := ln.Accept()
		if err != nil {
			log.Fatal("get client connection error: ", err)
		}

		go handleConnection(conn)
	}
}
`

**Comment by f4nff** [comment]
socks list :http://www.socks24.org/

**Comment by TuxCoding** [comment]
You are can to submit a pull request if you want to.

**Comment by f4nff** [comment]
Then you correct the first bug it, I found a tool python, I do not intend to pay

**Comment by f4nff** [comment]
https://github.com/BeastsMC/SOCKS-Proxy-Checker

I found this, to be better use, you can try to fix my bug, you are willing to take the initiative lies in you, i just submit bug

**Comment by f4nff** [comment]
If you fix it, I'd be happy to test it
